import type { Country } from '../shared/types';

export const mockCountries: Country[] = [
  {
    cca3: 'USA',
    name: { common: 'United States', official: 'United States of America' },
    flags: { png: 'https://flagcdn.com/w320/us.png', svg: 'https://flagcdn.com/us.svg', alt: 'The flag of the United States' },
    capital: ['Washington, D.C.'],
    region: 'Americas',
    population: 331900000,
  },
  {
    cca3: 'GBR',
    name: { common: 'United Kingdom', official: 'United Kingdom of Great Britain and Northern Ireland' },
    flags: { png: 'https://flagcdn.com/w320/gb.png', svg: 'https://flagcdn.com/gb.svg', alt: 'The flag of the United Kingdom' },
    capital: ['London'],
    region: 'Europe',
    population: 67530000,
  },
  {
    cca3: 'FRA',
    name: { common: 'France', official: 'French Republic' },
    flags: { png: 'https://flagcdn.com/w320/fr.png', svg: 'https://flagcdn.com/fr.svg', alt: 'The flag of France' },
    capital: ['Paris'],
    region: 'Europe',
    population: 67970000,
  },
  {
    cca3: 'DEU',
    name: { common: 'Germany', official: 'Federal Republic of Germany' },
    flags: { png: 'https://flagcdn.com/w320/de.png', svg: 'https://flagcdn.com/de.svg', alt: 'The flag of Germany' },
    capital: ['Berlin'],
    region: 'Europe',
    population: 83370000,
  },
  {
    cca3: 'ITA',
    name: { common: 'Italy', official: 'Italian Republic' },
    flags: { png: 'https://flagcdn.com/w320/it.png', svg: 'https://flagcdn.com/it.svg', alt: 'The flag of Italy' },
    capital: ['Rome'],
    region: 'Europe',
    population: 58940000,
  },
  {
    cca3: 'ESP',
    name: { common: 'Spain', official: 'Kingdom of Spain' },
    flags: { png: 'https://flagcdn.com/w320/es.png', svg: 'https://flagcdn.com/es.svg', alt: 'The flag of Spain' },
    capital: ['Madrid'],
    region: 'Europe',
    population: 47560000,
  },
  {
    cca3: 'PRT',
    name: { common: 'Portugal', official: 'Portuguese Republic' },
    flags: { png: 'https://flagcdn.com/w320/pt.png', svg: 'https://flagcdn.com/pt.svg', alt: 'The flag of Portugal' },
    capital: ['Lisbon'],
    region: 'Europe',
    population: 10410000,
  },
  {
    cca3: 'NLD',
    name: { common: 'Netherlands', official: 'Kingdom of the Netherlands' },
    flags: { png: 'https://flagcdn.com/w320/nl.png', svg: 'https://flagcdn.com/nl.svg', alt: 'The flag of the Netherlands' },
    capital: ['Amsterdam'],
    region: 'Europe',
    population: 17530000,
  },
  {
    cca3: 'BEL',
    name: { common: 'Belgium', official: 'Kingdom of Belgium' },
    flags: { png: 'https://flagcdn.com/w320/be.png', svg: 'https://flagcdn.com/be.svg', alt: 'The flag of Belgium' },
    capital: ['Brussels'],
    region: 'Europe',
    population: 11590000,
  },
  {
    cca3: 'CHE',
    name: { common: 'Switzerland', official: 'Swiss Confederation' },
    flags: { png: 'https://flagcdn.com/w320/ch.png', svg: 'https://flagcdn.com/ch.svg', alt: 'The flag of Switzerland' },
    capital: ['Bern'],
    region: 'Europe',
    population: 8715000,
  },
  {
    cca3: 'AUT',
    name: { common: 'Austria', official: 'Republic of Austria' },
    flags: { png: 'https://flagcdn.com/w320/at.png', svg: 'https://flagcdn.com/at.svg', alt: 'The flag of Austria' },
    capital: ['Vienna'],
    region: 'Europe',
    population: 9042000,
  },
  {
    cca3: 'POL',
    name: { common: 'Poland', official: 'Republic of Poland' },
    flags: { png: 'https://flagcdn.com/w320/pl.png', svg: 'https://flagcdn.com/pl.svg', alt: 'The flag of Poland' },
    capital: ['Warsaw'],
    region: 'Europe',
    population: 37840000,
  },
  {
    cca3: 'UKR',
    name: { common: 'Ukraine', official: 'Ukraine' },
    flags: { png: 'https://flagcdn.com/w320/ua.png', svg: 'https://flagcdn.com/ua.svg', alt: 'The flag of Ukraine' },
    capital: ['Kyiv'],
    region: 'Europe',
    population: 38000000,
  },
  {
    cca3: 'RUS',
    name: { common: 'Russia', official: 'Russian Federation' },
    flags: { png: 'https://flagcdn.com/w320/ru.png', svg: 'https://flagcdn.com/ru.svg', alt: 'The flag of Russia' },
    capital: ['Moscow'],
    region: 'Europe',
    population: 144444359,
  },
  {
    cca3: 'JPN',
    name: { common: 'Japan', official: 'Japan' },
    flags: { png: 'https://flagcdn.com/w320/jp.png', svg: 'https://flagcdn.com/jp.svg', alt: 'The flag of Japan' },
    capital: ['Tokyo'],
    region: 'Asia',
    population: 125124000,
  },
  {
    cca3: 'CHN',
    name: { common: 'China', official: "People's Republic of China" },
    flags: { png: 'https://flagcdn.com/w320/cn.png', svg: 'https://flagcdn.com/cn.svg', alt: 'The flag of China' },
    capital: ['Beijing'],
    region: 'Asia',
    population: 1412000000,
  },
  {
    cca3: 'IND',
    name: { common: 'India', official: 'Republic of India' },
    flags: { png: 'https://flagcdn.com/w320/in.png', svg: 'https://flagcdn.com/in.svg', alt: 'The flag of India' },
    capital: ['New Delhi'],
    region: 'Asia',
    population: 1417173173,
  },
  {
    cca3: 'AUS',
    name: { common: 'Australia', official: 'Commonwealth of Australia' },
    flags: { png: 'https://flagcdn.com/w320/au.png', svg: 'https://flagcdn.com/au.svg', alt: 'The flag of Australia' },
    capital: ['Canberra'],
    region: 'Oceania',
    population: 26068792,
  },
  {
    cca3: 'BRA',
    name: { common: 'Brazil', official: 'Federative Republic of Brazil' },
    flags: { png: 'https://flagcdn.com/w320/br.png', svg: 'https://flagcdn.com/br.svg', alt: 'The flag of Brazil' },
    capital: ['Brasília'],
    region: 'Americas',
    population: 215313498,
  },
  {
    cca3: 'MEX',
    name: { common: 'Mexico', official: 'Mexican United States' },
    flags: { png: 'https://flagcdn.com/w320/mx.png', svg: 'https://flagcdn.com/mx.svg', alt: 'The flag of Mexico' },
    capital: ['Mexico City'],
    region: 'Americas',
    population: 128932753,
  },
];
