import type { Country } from '../shared/types';

/** Used as fallback when the upstream API is unreachable */
export const mockCountries: Country[] = [
  {
    cca3: 'DEU',
    name: { common: 'Germany', official: 'Federal Republic of Germany' },
    flags: { png: 'https://flagcdn.com/w320/de.png', svg: 'https://flagcdn.com/de.svg', alt: 'Flag of Germany' },
    capital: ['Berlin'],
    region: 'Europe',
    population: 83240525,
  },
  {
    cca3: 'FRA',
    name: { common: 'France', official: 'French Republic' },
    flags: { png: 'https://flagcdn.com/w320/fr.png', svg: 'https://flagcdn.com/fr.svg', alt: 'Flag of France' },
    capital: ['Paris'],
    region: 'Europe',
    population: 67391582,
  },
  {
    cca3: 'ESP',
    name: { common: 'Spain', official: 'Kingdom of Spain' },
    flags: { png: 'https://flagcdn.com/w320/es.png', svg: 'https://flagcdn.com/es.svg', alt: 'Flag of Spain' },
    capital: ['Madrid'],
    region: 'Europe',
    population: 47351567,
  },
  {
    cca3: 'ITA',
    name: { common: 'Italy', official: 'Italian Republic' },
    flags: { png: 'https://flagcdn.com/w320/it.png', svg: 'https://flagcdn.com/it.svg', alt: 'Flag of Italy' },
    capital: ['Rome'],
    region: 'Europe',
    population: 59554023,
  },
  {
    cca3: 'POL',
    name: { common: 'Poland', official: 'Republic of Poland' },
    flags: { png: 'https://flagcdn.com/w320/pl.png', svg: 'https://flagcdn.com/pl.svg', alt: 'Flag of Poland' },
    capital: ['Warsaw'],
    region: 'Europe',
    population: 37950802,
  },
  {
    cca3: 'USA',
    name: { common: 'United States', official: 'United States of America' },
    flags: { png: 'https://flagcdn.com/w320/us.png', svg: 'https://flagcdn.com/us.svg', alt: 'Flag of the United States' },
    capital: ['Washington, D.C.'],
    region: 'Americas',
    population: 329484123,
  },
  {
    cca3: 'BRA',
    name: { common: 'Brazil', official: 'Federative Republic of Brazil' },
    flags: { png: 'https://flagcdn.com/w320/br.png', svg: 'https://flagcdn.com/br.svg', alt: 'Flag of Brazil' },
    capital: ['Brasília'],
    region: 'Americas',
    population: 212559409,
  },
  {
    cca3: 'CAN',
    name: { common: 'Canada', official: 'Canada' },
    flags: { png: 'https://flagcdn.com/w320/ca.png', svg: 'https://flagcdn.com/ca.svg', alt: 'Flag of Canada' },
    capital: ['Ottawa'],
    region: 'Americas',
    population: 38005238,
  },
  {
    cca3: 'MEX',
    name: { common: 'Mexico', official: 'United Mexican States' },
    flags: { png: 'https://flagcdn.com/w320/mx.png', svg: 'https://flagcdn.com/mx.svg', alt: 'Flag of Mexico' },
    capital: ['Mexico City'],
    region: 'Americas',
    population: 128932753,
  },
  {
    cca3: 'ARG',
    name: { common: 'Argentina', official: 'Argentine Republic' },
    flags: { png: 'https://flagcdn.com/w320/ar.png', svg: 'https://flagcdn.com/ar.svg', alt: 'Flag of Argentina' },
    capital: ['Buenos Aires'],
    region: 'Americas',
    population: 45376763,
  },
  {
    cca3: 'CHN',
    name: { common: 'China', official: "People's Republic of China" },
    flags: { png: 'https://flagcdn.com/w320/cn.png', svg: 'https://flagcdn.com/cn.svg', alt: 'Flag of China' },
    capital: ['Beijing'],
    region: 'Asia',
    population: 1402112000,
  },
  {
    cca3: 'JPN',
    name: { common: 'Japan', official: 'Japan' },
    flags: { png: 'https://flagcdn.com/w320/jp.png', svg: 'https://flagcdn.com/jp.svg', alt: 'Flag of Japan' },
    capital: ['Tokyo'],
    region: 'Asia',
    population: 125681593,
  },
  {
    cca3: 'IND',
    name: { common: 'India', official: 'Republic of India' },
    flags: { png: 'https://flagcdn.com/w320/in.png', svg: 'https://flagcdn.com/in.svg', alt: 'Flag of India' },
    capital: ['New Delhi'],
    region: 'Asia',
    population: 1380004385,
  },
  {
    cca3: 'KOR',
    name: { common: 'South Korea', official: 'Republic of Korea' },
    flags: { png: 'https://flagcdn.com/w320/kr.png', svg: 'https://flagcdn.com/kr.svg', alt: 'Flag of South Korea' },
    capital: ['Seoul'],
    region: 'Asia',
    population: 51780579,
  },
  {
    cca3: 'TUR',
    name: { common: 'Turkey', official: 'Republic of Turkey' },
    flags: { png: 'https://flagcdn.com/w320/tr.png', svg: 'https://flagcdn.com/tr.svg', alt: 'Flag of Turkey' },
    capital: ['Ankara'],
    region: 'Asia',
    population: 84339067,
  },
  {
    cca3: 'EGY',
    name: { common: 'Egypt', official: 'Arab Republic of Egypt' },
    flags: { png: 'https://flagcdn.com/w320/eg.png', svg: 'https://flagcdn.com/eg.svg', alt: 'Flag of Egypt' },
    capital: ['Cairo'],
    region: 'Africa',
    population: 102334403,
  },
  {
    cca3: 'NGA',
    name: { common: 'Nigeria', official: 'Federal Republic of Nigeria' },
    flags: { png: 'https://flagcdn.com/w320/ng.png', svg: 'https://flagcdn.com/ng.svg', alt: 'Flag of Nigeria' },
    capital: ['Abuja'],
    region: 'Africa',
    population: 206139587,
  },
  {
    cca3: 'ZAF',
    name: { common: 'South Africa', official: 'Republic of South Africa' },
    flags: { png: 'https://flagcdn.com/w320/za.png', svg: 'https://flagcdn.com/za.svg', alt: 'Flag of South Africa' },
    capital: ['Pretoria'],
    region: 'Africa',
    population: 59308690,
  },
  {
    cca3: 'KEN',
    name: { common: 'Kenya', official: 'Republic of Kenya' },
    flags: { png: 'https://flagcdn.com/w320/ke.png', svg: 'https://flagcdn.com/ke.svg', alt: 'Flag of Kenya' },
    capital: ['Nairobi'],
    region: 'Africa',
    population: 53771296,
  },
  {
    cca3: 'AUS',
    name: { common: 'Australia', official: 'Commonwealth of Australia' },
    flags: { png: 'https://flagcdn.com/w320/au.png', svg: 'https://flagcdn.com/au.svg', alt: 'Flag of Australia' },
    capital: ['Canberra'],
    region: 'Oceania',
    population: 25687041,
  },
];

export const mockCountryDetails: Record<string, {
  name: { common: string; official: string };
  flags: { svg: string; alt?: string };
  subregion?: string;
  languages?: Record<string, string>;
}> = {
  deu: { name: { common: 'Germany', official: 'Federal Republic of Germany' }, flags: { svg: 'https://flagcdn.com/de.svg', alt: 'Flag of Germany' }, subregion: 'Western Europe', languages: { deu: 'German' } },
  fra: { name: { common: 'France', official: 'French Republic' }, flags: { svg: 'https://flagcdn.com/fr.svg', alt: 'Flag of France' }, subregion: 'Western Europe', languages: { fra: 'French' } },
  esp: { name: { common: 'Spain', official: 'Kingdom of Spain' }, flags: { svg: 'https://flagcdn.com/es.svg', alt: 'Flag of Spain' }, subregion: 'Southern Europe', languages: { spa: 'Spanish' } },
  ita: { name: { common: 'Italy', official: 'Italian Republic' }, flags: { svg: 'https://flagcdn.com/it.svg', alt: 'Flag of Italy' }, subregion: 'Southern Europe', languages: { ita: 'Italian' } },
  pol: { name: { common: 'Poland', official: 'Republic of Poland' }, flags: { svg: 'https://flagcdn.com/pl.svg', alt: 'Flag of Poland' }, subregion: 'Central Europe', languages: { pol: 'Polish' } },
  usa: { name: { common: 'United States', official: 'United States of America' }, flags: { svg: 'https://flagcdn.com/us.svg', alt: 'Flag of the United States' }, subregion: 'North America', languages: { eng: 'English' } },
  bra: { name: { common: 'Brazil', official: 'Federative Republic of Brazil' }, flags: { svg: 'https://flagcdn.com/br.svg', alt: 'Flag of Brazil' }, subregion: 'South America', languages: { por: 'Portuguese' } },
  can: { name: { common: 'Canada', official: 'Canada' }, flags: { svg: 'https://flagcdn.com/ca.svg', alt: 'Flag of Canada' }, subregion: 'North America', languages: { eng: 'English', fra: 'French' } },
  mex: { name: { common: 'Mexico', official: 'United Mexican States' }, flags: { svg: 'https://flagcdn.com/mx.svg', alt: 'Flag of Mexico' }, subregion: 'North America', languages: { spa: 'Spanish' } },
  arg: { name: { common: 'Argentina', official: 'Argentine Republic' }, flags: { svg: 'https://flagcdn.com/ar.svg', alt: 'Flag of Argentina' }, subregion: 'South America', languages: { spa: 'Spanish' } },
  chn: { name: { common: 'China', official: "People's Republic of China" }, flags: { svg: 'https://flagcdn.com/cn.svg', alt: 'Flag of China' }, subregion: 'Eastern Asia', languages: { zho: 'Chinese' } },
  jpn: { name: { common: 'Japan', official: 'Japan' }, flags: { svg: 'https://flagcdn.com/jp.svg', alt: 'Flag of Japan' }, subregion: 'Eastern Asia', languages: { jpn: 'Japanese' } },
  ind: { name: { common: 'India', official: 'Republic of India' }, flags: { svg: 'https://flagcdn.com/in.svg', alt: 'Flag of India' }, subregion: 'Southern Asia', languages: { eng: 'English', hin: 'Hindi' } },
  kor: { name: { common: 'South Korea', official: 'Republic of Korea' }, flags: { svg: 'https://flagcdn.com/kr.svg', alt: 'Flag of South Korea' }, subregion: 'Eastern Asia', languages: { kor: 'Korean' } },
  tur: { name: { common: 'Turkey', official: 'Republic of Turkey' }, flags: { svg: 'https://flagcdn.com/tr.svg', alt: 'Flag of Turkey' }, subregion: 'Western Asia', languages: { tur: 'Turkish' } },
  egy: { name: { common: 'Egypt', official: 'Arab Republic of Egypt' }, flags: { svg: 'https://flagcdn.com/eg.svg', alt: 'Flag of Egypt' }, subregion: 'Northern Africa', languages: { ara: 'Arabic' } },
  nga: { name: { common: 'Nigeria', official: 'Federal Republic of Nigeria' }, flags: { svg: 'https://flagcdn.com/ng.svg', alt: 'Flag of Nigeria' }, subregion: 'Western Africa', languages: { eng: 'English' } },
  zaf: { name: { common: 'South Africa', official: 'Republic of South Africa' }, flags: { svg: 'https://flagcdn.com/za.svg', alt: 'Flag of South Africa' }, subregion: 'Southern Africa', languages: { afr: 'Afrikaans', eng: 'English' } },
  ken: { name: { common: 'Kenya', official: 'Republic of Kenya' }, flags: { svg: 'https://flagcdn.com/ke.svg', alt: 'Flag of Kenya' }, subregion: 'Eastern Africa', languages: { eng: 'English', swa: 'Swahili' } },
  aus: { name: { common: 'Australia', official: 'Commonwealth of Australia' }, flags: { svg: 'https://flagcdn.com/au.svg', alt: 'Flag of Australia' }, subregion: 'Australia and New Zealand', languages: { eng: 'English' } },
};
